import type { Metadata } from "next";
import "./globals.css";
// import { Actor } from 'next/font/google'
import { Poppins } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
// import { DM_Sans } from 'next/font/google'
// import { Outfit } from 'next/font/google'
// import { Space_Grotesk } from 'next/font/google'

const actor = Poppins({
  weight: "400", // if single weight, otherwise you use array like [400, 500, 700],
  style: "normal", // if single style, otherwise you use array like ['normal', 'italic']
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={actor.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
